AWSTemplateFormatVersion: 2010-09-09
Description: 'Mobile Purchases DynamoDB'

Parameters:
  Stack:
    Description: Stack name
    Type: String
  App:
    Description: Application name
    Type: String
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
Resources:
  userPurchasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Stage}-${Stack}-user-purchases
      AttributeDefinitions:
        - AttributeName: userIdColonAppId
          AttributeType: S
      KeySchema:
        - AttributeName: userIdColonAppId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: 'ttl'
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  UserSubscriptionEventsTableV2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Stage}-subscription-events-v2
      AttributeDefinitions:
        - AttributeName: subscriptionId
          AttributeType: S
        - AttributeName: timestampAndType
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: subscriptionId
          KeyType: HASH
        - AttributeName: timestampAndType
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: date-timestamp-index-v2
          KeySchema:
            - AttributeName: date
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  SubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Stage}-subscriptions
      AttributeDefinitions:
        - AttributeName: subscriptionId
          AttributeType: S
        - AttributeName: endTimestamp
          AttributeType: S
      KeySchema:
        - AttributeName: subscriptionId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      GlobalSecondaryIndexes:
        - IndexName: ios-endTimestamp-revalidation-index
          KeySchema:
            - AttributeName: subscriptionId
              KeyType: HASH
            - AttributeName: endTimestamp
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - auto_renew_status
              - latest_receipt_info
            ProjectionType: INCLUDE
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  UserSubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Stage}-user-subscriptions
      AttributeDefinitions:
        - AttributeName: subscriptionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: subscriptionId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: subscriptionId-userId
          KeySchema:
            - AttributeName: subscriptionId
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

Outputs:
  SubscriptionTableStream:
    Description: The ARN of the dynamo DB stream
    Value: !GetAtt SubscriptionTable.StreamArn
    Export:
      Name: !Sub ${App}-${Stage}-subscriptions-stream-arn
