AWSTemplateFormatVersion: 2010-09-09
Description: FeastGoogleAcquisitionEventsLambda

Parameters:
  Stack:
    Description: Stack name
    Type: String
  App:
    Description: Application name
    Type: String
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String

Resources:
  FeastGoogleAcquisitionEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${App}-${Stage}-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FeastGoogleAcquisitionEventsDlq.Arn
        maxReceiveCount: 5
      Tags:
        - Key: gu:repo
          Value: guardian/mobile-purchases
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage
        - Key: App
          Value: !Ref App
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  FeastGoogleAcquisitionEventsLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Join
          - ''
          - - 'arn:'
            - !Ref AWS::Partition
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Tags:
        - Key: App
          Value: !Ref App
        - Key: gu:repo
          Value: guardian/mobile-purchases
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage

  FeastGoogleAcquisitionEventsLambdaServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource: !GetAtt FeastGoogleAcquisitionEventsQueue.Arn
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:'
                  - !Ref AWS::Partition
                  - ':s3:::'
                  - !Ref DeployBucket
              - !Join
                - ''
                - - 'arn:'
                  - !Ref AWS::Partition
                  - ':s3:::'
                  - !Ref DeployBucket
                  - !Sub ${Stack}/${Stage}/${App}-feast-google-acquisition-events/${App}-feast-google-acquisition-events.zip
          - Action: ssm:GetParametersByPath
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:ssm:'
                - !Ref AWS::Region
                - ':'
                - !Ref AWS::AccountId
                - ':parameter/PROD/mobile/feast-google-acquisition-events'
          - Action:
              - ssm:GetParameters
              - ssm:GetParameter
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:ssm:'
                - !Ref AWS::Region
                - ':'
                - !Ref AWS::AccountId
                - ':parameter/PROD/mobile/feast-google-acquisition-events/*'
        Version: '2012-10-17'
      PolicyName: FeastGoogleAcquisitionEventsLambdaServiceRoleDefaultPolicy
      Roles:
        - !Ref FeastGoogleAcquisitionEventsLambdaServiceRole

  FeastGoogleAcquisitionEventsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}-feast-google-acquisition-events/feast-google-acquisition-events.zip
      Description: An SQS triggered lambda to process acquisition events for android devices and write to event buffer.
      Environment:
        Variables:
          App: !Ref App
          Stack: !Ref Stack
          Stage: !Ref Stage
          STACK: !Ref Stack
          STAGE: !Ref Stage
          APP: !Ref App
      FunctionName: !Sub ${App}-feast-google-acquisition-events-${Stage}
      Handler: feast-google-acquisition-events.handler
      MemorySize: 1024
      Role: !GetAtt FeastGoogleAcquisitionEventsLambdaServiceRole.Arn
      Runtime: nodejs20.x
      Tags:
        - Key: App
          Value: !Ref App
        - Key: gu:repo
          Value: guardian/mobile-purchases
        - Key: Stack
          Value: !Ref Stack
        - Key: Stage
          Value: !Ref Stage
      Timeout: 300
    DependsOn:
      - FeastGoogleAcquisitionEventsLambdaServiceRoleDefaultPolicy
      - FeastGoogleAcquisitionEventsLambdaServiceRole

  FeastGoogleAcquisitionEventsSqsEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt FeastGoogleAcquisitionEventsQueue.Arn
      FunctionName: !Ref FeastGoogleAcquisitionEventsLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures

   FeastGoogleAcquisitionEventsLambdaS3inlinepolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::mobile-dist/mobile/${Stage}/${App}-feast-google-acquisition-events/
        Version: '2012-10-17'
      PolicyName: S3inlinepolicy
      Roles:
        - !Ref FeastGoogleAcquisitionEventsLambdaServiceRole

  FeastGoogleAcquisitionEventsLambdaSecretManagerAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: secretsmanager:GetSecretValue
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:secretsmanager:'
                  - !Ref AWS::Region
                  - ':'
                  - !Ref AWS::AccountId
                  - !Sub :secret:${Stage}/${App}-feast-google-acquisition-events/*
        Version: '2012-10-17'
      PolicyName: Secretmanageraccesspolicy79659139
      Roles:
        - !Ref FeastGoogleAcquisitionEventsLambdaServiceRole