import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { APIGatewayProxyEvent } from 'aws-lambda';
import { Stage } from '../utils/appIdentity';
import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm';
import { JWT } from 'google-auth-library';

const s3Client = new S3Client({
	region: process.env.AWS_REGION || 'us-east-1',
});

const ssmClient = new SSMClient({
	region: process.env.AWS_REGION || 'us-east-1',
});

interface GoogleServiceAccountCredentials {
	type: string;
	project_id: string;
	private_key_id: string;
	private_key: string;
	client_email: string;
	client_id: string;
	auth_uri: string;
	token_uri: string;
	auth_provider_x509_cert_url: string;
	client_x509_cert_url: string;
}

async function getGoogleCredentials(): Promise<GoogleServiceAccountCredentials> {
	const parameterName = `/mobile-purchases/${Stage}/google-oauth-lambda/google.serviceAccountJson`;

	try {
		const command = new GetParameterCommand({
			Name: parameterName,
			WithDecryption: true,
		});

		const response = await ssmClient.send(command);

		if (!response.Parameter?.Value) {
			throw new Error('No credentials found in SSM');
		}

		// Parse the JSON string from SSM
		return JSON.parse(response.Parameter.Value);
	} catch (error) {
		console.error('Error retrieving credentials from SSM:', error);
		throw error;
	}
}

async function getBearerToken(): Promise<string> {
	const credentials = await getGoogleCredentials();

	const client = new JWT({
		email: credentials.client_email,
		key: credentials.private_key,
		scopes: ['https://www.googleapis.com/auth/androidpublisher'],
	});

	const token = await client.authorize();
	return token.access_token!;
}

function getFormattedDateTime(): string {
	// Return a datetime in the format: "Thu Jun 18 11:54:00 UTC 2026"
	//
	// Note that we attempt to be backward compatible with
	// the existing datetime generated by the scala code that this is going to
	// eventually replace.

	const date = new Date();
	return date.toUTCString().replace('GMT', 'UTC').replace(',', '');
}

export const handler = async (_event: APIGatewayProxyEvent) => {
	console.log('[0a433488] starting mobile-purchases-googleoauth2');

	try {
		// The bucket name is hardcoded in the existing scala code,
		// so we are doing the same here for simplicity.
		const bucketName = 'gu-mobile-access-tokens';

		const bearerToken = await getBearerToken();

		const data = {
			token: bearerToken,
			expiry: getFormattedDateTime(),
		};

		// In this version we are generating  access_token2.json to sit along side
		// access_token.json, which is still being generated.
		const filename = 'access_token.json';

		const locationKey = `${Stage}/google-play-developer-api/${filename}`;

		const command = new PutObjectCommand({
			Bucket: bucketName,
			Key: locationKey,
			Body: JSON.stringify(data, null, 2),
			ContentType: 'application/json',
		});

		const response = await s3Client.send(command);

		console.log(`File uploaded successfully: ${locationKey}`);
		console.log('ETag:', response.ETag);
	} catch (error) {
		console.error('Error uploading `${locationKey}` to S3:', error);
	}
};
