import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { APIGatewayProxyEvent } from 'aws-lambda';

const s3Client = new S3Client({
	region: process.env.AWS_REGION || 'us-east-1',
});

function getFormattedDateTime(): string {
	// Return a datetime in the format: "Thu Jun 18 11:54:00 UTC 2026"
	//
	// Note that we attempt to be backward compatible with
	// the existing datetime generated by the scala code that this is going to
	// eventually replace.

	const date = new Date();
	return date.toUTCString().replace('GMT', 'UTC').replace(',', '');
}

export const handler = async (_event: APIGatewayProxyEvent) => {
	console.log('[0a433488] starting mobile-purchases-google-oauth2');

	try {
		// The bucket name is hardcoded in the existing scala code,
		// so we are doing the same here for simplicity.
		const bucketName = 'gu-mobile-access-tokens';

		const data = {
			token: 'fake-token',
			expiry: getFormattedDateTime(),
		};

		// In this version we are generating  access_token2.json to sit along side
		// access_token.json, which is still being generated.
		const filename = 'access_token2.json';

		// We still have the stage hardcoded because we do not yet have support for
		// retrieving it.
		const locationKey = `PROD/google-play-developer-api/${filename}`;

		const command = new PutObjectCommand({
			Bucket: bucketName,
			Key: locationKey,
			Body: JSON.stringify(data, null, 2),
			ContentType: 'application/json',
		});

		const response = await s3Client.send(command);

		console.log(`File uploaded successfully: ${locationKey}`);
		console.log('ETag:', response.ETag);
	} catch (error) {
		console.error('Error uploading `${locationKey}` to S3:', error);
	}
};
